gulpfile.js

Resolved lints in gulpfile, removed watchify (previous commit) and added back the "lint" gulp task file which was accidentally removed in the process.

[Fixes #103676304] Added back linting gulp task, accidentally removed

---

app/scripts/controllers/about.js

Add new contributors to about page.
[Finishes #111597280]

About page

---

app/scripts/controllers/event.js
app/styles/app.less
app/views/view-event.jade
migrations/create-reviews.js
server/controllers/events.js
server/controllers/review.js
server/models/relationships.js

refers to [#112778257]
Update database relationships to allow one to many mapping between 'events' and 'reviews'
Modify server 'reviews' controller to accomodate events
Add review section to event description page
Modify frontend 'events' controller to allow adding of reviews by users

Add event review section

---

server/config/database.js

[Delivers #115584649]
- Include staging key in database configuration

Add staging config key

---

migrations/20160210123033-addcolumn_type.js
migrations/20160210124231-addcolumn_category_id.js

[Delivers #115679387]
- Allow null for tables with pre exiting data

Alter Heroku migration scripts

---

.codeclimate.yml

[Delivers #116020999]
- Remove unnecessary quote

Fix code climate gpa report

---

app/scripts/controllers/items.js
circle.yml
tests/unit/client/controllers/items.spec.js

It allows users to be able to post and see product reviews.

#119189457 Fix bug users not being able to post product reviews

---

.sequelizerc
app/views/home.jade
server/config/database.json

Refers to [#119187717]
- Change Placeholder message to a more descriptive message
- Change Hero text to a more descriptive message

Edit the copy in the app to be more descriptive

---

app/index.jade

[Finishes #119189947] Add favicon to index html

---

app/views/login.jade
server/config/passport.config.js
server/routes/auth/facebook.auth.js

- Remove focus from input fields for social login
- Change Facebook Auth Config in Server file.
- Change Facebook variables in passport-facebook.js file

[#119263005] Fix Social Login

---

app/styles/app.less

- Reduce the font size of the user email address
- Increase the font size of the username

[#112886161] Modify the outlook of user profile

---

app/views/all-events.jade
app/views/events.jade
app/views/home.jade
app/views/items.jade

- Make event cards clickable
- Make products cards clickable

[#119189183] Make cards clickable

---

app/scripts/application.js
app/scripts/controllers/event.js
app/scripts/controllers/items.js
app/scripts/services/items.js
app/views/events.jade
app/views/items.jade
server/controllers/items.js
server/routes/items.js
tests/unit/client/controllers/items.spec.js

- Add popular category to products and events

[#120856935] Implement popular events/products categories

---

app/scripts/application.js
app/scripts/controllers/login.js

- Add error message to login.js file
- Create form-validator.js file

[#120663263] Add sign-up error message

---

app/scripts/controllers/event.js
app/scripts/controllers/items.js
app/styles/app.less
app/views/view-event.jade
app/views/view-item.jade
server/controllers/review.js
tests/unit/client/controllers/event.spec.js
tests/unit/client/controllers/items.spec.js
tests/unit/client/controllers/user-profile/events.spec.js

1. Users should be able to edit their review on products and events.
1. Users should be able to delete their review on products and events.
1. Users should not be able to review an event or product more than once.

[Finishes #113811327] Complete CRUD operation on items/products review

---

app/scripts/application.js
app/scripts/controllers/home.js
app/scripts/controllers/search.js
app/scripts/directives/back-img.js
app/scripts/services/events.js
app/styles/app.less
app/views/home.jade
app/views/search.jade
gulpfile.js
server/controllers/events.js
server/routes/events.js
tests/server/resources/events.spec.js

Users should be able to search from homepage

[Finsihes #121117411] Adds search feature and tests

---

app/scripts/controllers/event.js
app/views/home.jade

This PR allows users that are not logged in to view Events

[Fixes #127068987] Users can view Events even when not logged in

---

app/styles/app.less

fix transparent date picker

---

app/styles/app.less
app/views/view-event.jade
app/views/view-item.jade
server/controllers/events.js
server/controllers/items.js

1. Users should be able to see the name of the reviewer
1. The review also displays the avatar of the reviewer

[Fix #122478221] Add user data to review information

---

.jshintrc
app/scripts/controllers/home.js
app/shared/head.jade
app/views/home.jade
bower.json
server/routes/events.js

This PR adds days left to events on landing page cards

[#126671797] add days left to events on landing screen cards

---

app/scripts/application.js
app/scripts/controllers/home.js
app/scripts/directives/back-img.js
app/scripts/directives/ng-custom-event.js
app/views/home.jade

This PR hides the placeholder in search input onfocus and shows it onblur

[#127069057] Bug/hide placeholder landing screen

---

app/scripts/directives/ng-custom-event.js

fix hide placeholder on landing screen

[#127069057] hide placeholder on focus then show on blur

---

.gitignore
circle.yml
gulpfile.js
protractor.conf.js
tests/e2e/test.e2e.js

[Finishes #126985775] Fix e2e configuration bug

---

app/scripts/application.js
app/scripts/directives/vvida-card.js
app/styles/app.less
app/views/home.jade

This PR converts the event cards to a directive.

[#127636969] add event card directive

---

app/scripts/controllers/event.js
app/scripts/controllers/header.js
app/styles/app.less
app/views/view-event.jade
tests/unit/client/controllers/event.spec.js
tests/unit/client/controllers/header.spec.js

Story ID: #127070783
This PR completes the redesign of single event/review page.

Finishes [#127070783] Redesign single event/Review page

---

app/scripts/directives/vvida-card.js
migrations/20160808111546-remove-products-table.js
tests/e2e/create-user.e2e.js
tests/e2e/edit-user.e2e.js

It resolves the Hound CI issues in #287 
[Delivers #130359143]

Fix HoundCI issues

---

server/controllers/events.js

Resolve the HoundCI issues in #286 
[Finishes #130359143]

Resolve HoundCI issues
